### ISSUE TITLE
Just a post to say it works flawlessly

### ISSUE THREAD

**Issue by tchirou** [vlacour97/alldebrid-watcher#11]
To anyone arriving in this GitHub and wondering if it works looking at the issues : yes it does !
Just installed on a Synology with the docker GUI and it does what it advertises beautifully. Be it one torrent with one file or one torrent with several files, it works as intended.
I was afraid it would also download files I manually upload on the alldebrid website and thanksfully it doesn’t.
This is perfect for me

The only minor thing is that the pushover notification “download started” arrives when the file download is completed

Many many thanks to the dev !

**Comment by vlacour97** [comment]
Hello

Thanks a lot for your message !
I'm glad the tool meets your needs so well :)

I will see how I can fix this problem. I'll let you know as soon as I have a PR about it ;)

See you soon !

**Comment by tchirou** [comment]
Hi Valentin

I hope you are well. Would you have any ETA about fixing the event "started" for the pushover notification ? 
I can't help myself to manually verify the file has started to download, which defeats the purpose  ;-)

Thanks a lot

**Comment by vlacour97** [comment]
Hello
A second version of the application is coming soon!
With even more possibilities and fixes concerning the problems encountered on the current version
I'll keep you posted on the progress, 90% of the work is done but there are still a few things to finish
I hope to have this finished by next week but time is not playing in my favor right now 😅
Best regards !

**Comment by tchirou** [comment]
Thanks a lot !!!

**Comment by vlacour97** [comment]
Before the release of the second version, I made a corrective version of 1.1.0 to correct your problem.
It's merged if you want :)
Enjoy! And don't hesitate to close this issue if the problem is solved on your side ;)

**Comment by tchirou** [comment]
It works beautifully as intended now !
i am really excited about the « new possibilities » you mentioned
Thanks a lot for the fix and everything

**Comment by tchirou** [comment]
Oups ! 
i had tried with a single file
Now I tried with a torrent with a dozen file and it started to download all of them simultaneously 
It seems the max parallel download variable (I had set it up with 1 file max) doesn’t work anymore

**Comment by vlacour97** [comment]
Arg I missed this error :x
I just finished v2.0.0 (the version I told you about) and the parallel download limitation system is more stable according to my tests
I had little time to test this version but it already has me much more stable :)
Waiting for your feedback
Good evenings ! :)

**Comment by tchirou** [comment]
Hi Valentin

So far it works great !

A few things : 
- the "}" is missing at the end of the description of the notifier : `{"stdout": "all", "pushover": ["download_start", "download_done"]`
- I personally prefer `File downloaded` rather than `Download finish`. It should at leats be `Download finished` instead `Download finish`. Also `The file X is being downloaded` of the previous version makes more sense than the new `The downlad of file X has been started`
- What `Download progess` should do and when ? I enabled it but I don't have any notification so far and how is it supposed to be triggered ? A countdown of X minutes ?
- Have you planned to integrate a means to pause/stop downloads, if it's possible ? 

It is great work! Just bought a coffee (or a beer) on Ko-Fi as very much deserved reward !!!

**Comment by vlacour97** [comment]
Hey !
Thank you so much for your feedback and your coffee (but yes i prefer beer ;)) ! 
For the first two points, I will make a correction in the evening
For the third point, the download progress is only avalaible for stdout, to avoid problems of quota in pushover. I think I will update the doc on this.
For the last point,  unfortunately this is not planned at the moment
If you want, you can create another issue to propose the functionality and I will see to implement it if this one is requested by other users ;) 

If it's okay for you, I'll close the issue once the changes are done ;)

**Comment by tchirou** [comment]
Thanks a lot !
