### ISSUE TITLE
Synchronous downloads

### ISSUE THREAD

**Issue by Bsmith101** [vlacour97/alldebrid-watcher#3]
Synchronous downloads would be a nice feature. I think I'm getting rate limited by alldebrid when trying to download a torrent with many large files.

**Comment by vlacour97** [comment]
Hello, 

I'm coming back to these topics a little late, sorry.  
If I understand your request correctly, you would like to be able to download several files from the same torrent synchronously (for example for a series, to have the first episodes available immediately)?  
I admit that it could be a good idea!  
Do you also concern the possibility of being able to download 1 torrent at a time?  

Best regards

**Comment by vlacour97** [comment]
This feature was release in version 1.1.0 of this tool
https://github.com/vlacour97/alldebrid-watcher/releases/tag/1.1.0
Use env variable MAX_PARALLELS_DOWNLOADS=1 for synchronious download
Enjoy ;)
