### ISSUE TITLE
Is it working ?

### ISSUE THREAD

**Issue by KoRnEr007** [vlacour97/alldebrid-watcher#4]
Hello,
i tried your script on docker... 
i put the .torrent on the folder but nothing is sent to alldebrid

best rgds
Jo

**Comment by vlacour97** [comment]
Hello, 

I will try to fix this problem.  
Can you send me the docker command you used and the possible logs you got on running (docker logs {container-id}) ?

Best Rgds
Thks

**Comment by vlacour97** [comment]
Since the subject is no longer current, I am closing the issue.
Best Regards
