### ISSUE TITLE
Server to Client, 1 file only torrents

### ISSUE THREAD

**Issue by jferris-** [vlacour97/alldebrid-watcher#5]
Probably pointless posting this, as it looks like the project is sadly dead.

I have noticed torrents aren't picked up from AllDebrid if the torrent contained more than one file. Is there any way to alter this?

**Comment by vlacour97** [comment]
Hello,
Thanks to your message I just remembered that I had opened this open source project!  
I'll see if I can do something 😉

**Comment by vlacour97** [comment]
Following my tests it is indeed possible to download several files offered by the same torrent
I tested with a series and all the episodes are downloaded well
Do you have an example of a torrent file where it doesn't work?
