### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by dreeck** [vlacour97/alldebrid-watcher#9]
>npm install ALLDEBRID_TOKEN=allbredid-token
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "ALLDEBRID_TOKEN=allbredid-token" of package "ALLDEBRID_TOKEN=allbredid-token": Tags may not have any characters that encodeURIComponent encodes.

**Comment by vlacour97** [comment]
Hello 
The command is wrong
After you clone the project, you need to write :

```
npm install
```

and after

```
ALLDEBRID_TOKEN=allbredid-token npm run start
```
